### PR TITLE
illision-mobile-apporch-done

### PR DESCRIPTION
**Pull request by FaizanKhan7**
# mobile-version

mobile(320)

# mobile-menu
mobile(320)menu
# mobile-section
mobile-section

# When reached 700px
700px

# when reached 700px (section)
700px(2)

#when reached 1000px
1000px

#when reached 1000px(section)
1000px(2)

### CODE REVIEW

**Comment by tajammul1996** [comment]
1. Add proper spacing in between sections.
2. Make image centered and width as 90%

**Comment by FaizanKhan7** [comment]
> 1. Add proper spacing in between sections.
> 2. Make image centered and width as 90%

done

**Review by tajammul1996 — APPROVED** [review]
Great job!

**Comment by FaizanKhan7** [comment]
> Great job!

thanks

**Pull request merged**
